apiVersion: v1
kind: ServiceAccount
metadata:
  name: epinio-installer
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: epinio-installer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: epinio-installer
  namespace: "{{ .Release.Namespace }}"
