apiVersion: v1
kind: ServiceAccount
metadata:
  name: epinio-installer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: epinio-installer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: epinio-installer
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: epinio-installer
  namespace: kube-system
spec:
  backoffLimit: 0
  template:
    metadata:
      name: epinio-installer
    spec:
      restartPolicy: Never
      serviceAccountName: epinio-installer
      containers:
      - name: install
        image: ghcr.io/manno/epinio-installer:latest
        imagePullPolicy: IfNotPresent
        command:
          - epinio
        args:
          - install

